version: '3.6'

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=${POSTGRES_USER:-retail}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-retail}
      - POSTGRES_DB=${POSTGRES_DB:-retail}
  rabbitmq:
    image: rabbitmq:3.9.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  
  retail-setup:
    build: 
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG:-true}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - database
